### PR TITLE
Add untracked function

### PR DESCRIPTION
**Pull request by dy**
@WebReflection I figured instead of making `peek` method create an effect (which doesn't look good), a high-level better solution would be exporting `untracked` function, same as preact signals does.

Wdyt?

### CODE REVIEW

**Comment by WebReflection** [comment]
@dy about this:

> instead of making peek method create an effect (which doesn't look good)

AFAIK the reason `.peek()` exists is to return the value directly whouch should have no side-effect ... what does not look good or why that's not enough?

> Wdyt?

I think this change looks good but I would like to better understand what we are trying to solve or if there's anything fundamentally broken in current `.peek()` implementation that I am overlooking at, thank you!

**Comment by dy** [comment]
> if there's anything fundamentally broken in current .peek()

Since `computed` is lazy, uninitialized `peek()` returns `undefined` now:
```js
let s = signal(1), c = computed(() => s.value)

c.peek() // undefined
c.value // 1
c.peek() // 1

```
Idk if that can be considered broken, but it's inconsistent with `c.value` and discrepancy with preact signals. To initialize `computed` we'd need to read its `c.value`, but if we run it in an effect, then it will be automatically subscribed...

So it's either needs to be initialized upon call, like `c.value` does, or there can be `untracked` function. I thought of [this one](https://x.com/_developit/status/1722654851803328804?s=20) first but then realized it's preact-signals only, it would not work here. So instead decided that proper `untracked` is better.

> what does not look good

Mainly `.peek()` doesn't fit aesthetics of signals: they don't have methods (eg. [ulive](https://github.com/kethan/ulive) doesn't have `peek`).

To track values we call `effect(() => s.value)`, it would look consistent to also make a call for untracked values `untracked(() => s.value)`.

**Comment by WebReflection** [comment]
I think peek for computed *might* be smarter in here but I see value in adding *untracked*.

**Comment by WebReflection** [comment]
it's in v2.1.0

**Pull request merged**
